const data = [
  {
    label: "10/01/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 0 },
      { label: "Company B", color: "#00cec9", image: "", value: 0 },
      { label: "Company C", color: "#0984e3", image: "", value: 0 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 0 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 0 },
      { label: "Company G", color: "#fab1a0", image: "", value: 0 },
      { label: "Company H", color: "#ff7675", image: "", value: 0 },
      { label: "Company I", color: "#fd79a8", image: "", value: 0 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 0 },
      { label: "Company K", color: "#e17055", image: "", value: 0 },
      { label: "Company L", color: "#d63031", image: "", value: 0 },
      { label: "Company M", color: "#e84393", image: "", value: 0 },
    ],
  },

  {
    label: "10/02/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 1 },
      { label: "Company B", color: "#00cec9", image: "", value: 3 },
      { label: "Company C", color: "#0984e3", image: "", value: 2 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 3 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 7 },
      { label: "Company G", color: "#fab1a0", image: "", value: 12 },
      { label: "Company H", color: "#ff7675", image: "", value: 10 },
      { label: "Company I", color: "#fd79a8", image: "", value: 8 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 4 },
      { label: "Company K", color: "#e17055", image: "", value: 1 },
      { label: "Company L", color: "#d63031", image: "", value: 2 },
      { label: "Company M", color: "#e84393", image: "", value: 5 },
    ],
  },

  {
    label: "10/03/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 3 },
      { label: "Company B", color: "#00cec9", image: "", value: 12 },
      { label: "Company C", color: "#0984e3", image: "", value: 8 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 9 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 15 },
      { label: "Company G", color: "#fab1a0", image: "", value: 7 },
      { label: "Company H", color: "#ff7675", image: "", value: 11 },
      { label: "Company I", color: "#fd79a8", image: "", value: 13 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 6 },
      { label: "Company K", color: "#e17055", image: "", value: 1 },
      { label: "Company L", color: "#d63031", image: "", value: 10 },
      { label: "Company M", color: "#e84393", image: "", value: 14 },
    ],
  },

  {
    label: "10/04/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 7 },
      { label: "Company B", color: "#00cec9", image: "", value: 13 },
      { label: "Company C", color: "#0984e3", image: "", value: 9 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 10 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 16 },
      { label: "Company G", color: "#fab1a0", image: "", value: 10 },
      { label: "Company H", color: "#ff7675", image: "", value: 12 },
      { label: "Company I", color: "#fd79a8", image: "", value: 14 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 11 },
      { label: "Company K", color: "#e17055", image: "", value: 2 },
      { label: "Company L", color: "#d63031", image: "", value: 15 },
      { label: "Company M", color: "#e84393", image: "", value: 14 },
    ],
  },

  {
    label: "10/05/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 14 },
      { label: "Company B", color: "#00cec9", image: "", value: 14 },
      { label: "Company C", color: "#0984e3", image: "", value: 16 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 22 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 18 },
      { label: "Company G", color: "#fab1a0", image: "", value: 10 },
      { label: "Company H", color: "#ff7675", image: "", value: 13 },
      { label: "Company I", color: "#fd79a8", image: "", value: 15 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 14 },
      { label: "Company K", color: "#e17055", image: "", value: 19 },
      { label: "Company L", color: "#d63031", image: "", value: 12 },
      { label: "Company M", color: "#e84393", image: "", value: 17 },
    ],
  },

  {
    label: "10/06/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 28 },
      { label: "Company B", color: "#00cec9", image: "", value: 25 },
      { label: "Company C", color: "#0984e3", image: "", value: 20 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 32 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 20 },
      { label: "Company G", color: "#fab1a0", image: "", value: 10 },
      { label: "Company H", color: "#ff7675", image: "", value: 14 },
      { label: "Company I", color: "#fd79a8", image: "", value: 18 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 15 },
      { label: "Company K", color: "#e17055", image: "", value: 3 },
      { label: "Company L", color: "#d63031", image: "", value: 21 },
      { label: "Company M", color: "#e84393", image: "", value: 19 },
    ],
  },

  {
    label: "10/07/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 32 },
      { label: "Company B", color: "#00cec9", image: "", value: 33 },
      { label: "Company C", color: "#0984e3", image: "", value: 28 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 40 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 26 },
      { label: "Company G", color: "#fab1a0", image: "", value: 14 },
      { label: "Company H", color: "#ff7675", image: "", value: 15 },
      { label: "Company I", color: "#fd79a8", image: "", value: 20 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 17 },
      { label: "Company K", color: "#e17055", image: "", value: 4 },
      { label: "Company L", color: "#d63031", image: "", value: 25 },
      { label: "Company M", color: "#e84393", image: "", value: 23 },
    ],
  },

  {
    label: "10/08/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 40 },
      { label: "Company B", color: "#00cec9", image: "", value: 42 },
      { label: "Company C", color: "#0984e3", image: "", value: 50 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 52 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 28 },
      { label: "Company G", color: "#fab1a0", image: "", value: 20 },
      { label: "Company H", color: "#ff7675", image: "", value: 16 },
      { label: "Company I", color: "#fd79a8", image: "", value: 21 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 17 },
      { label: "Company K", color: "#e17055", image: "", value: 7 },
      { label: "Company L", color: "#d63031", image: "", value: 33 },
      { label: "Company M", color: "#e84393", image: "", value: 25 },
    ],
  },

  {
    label: "10/09/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 42 },
      { label: "Company B", color: "#00cec9", image: "", value: 42 },
      { label: "Company C", color: "#0984e3", image: "", value: 44 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 64 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 36 },
      { label: "Company G", color: "#fab1a0", image: "", value: 20 },
      { label: "Company H", color: "#ff7675", image: "", value: 17 },
      { label: "Company I", color: "#fd79a8", image: "", value: 24 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 17 },
      { label: "Company K", color: "#e17055", image: "", value: 8 },
      { label: "Company L", color: "#d63031", image: "", value: 38 },
      { label: "Company M", color: "#e84393", image: "", value: 34 },
    ],
  },

  {
    label: "10/10/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 50 },
      { label: "Company B", color: "#00cec9", image: "", value: 48 },
      { label: "Company C", color: "#0984e3", image: "", value: 56 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 71 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 40 },
      { label: "Company G", color: "#fab1a0", image: "", value: 24 },
      { label: "Company H", color: "#ff7675", image: "", value: 18 },
      { label: "Company I", color: "#fd79a8", image: "", value: 26 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 20 },
      { label: "Company K", color: "#e17055", image: "", value: 11 },
      { label: "Company L", color: "#d63031", image: "", value: 42 },
      { label: "Company M", color: "#e84393", image: "", value: 38 },
    ],
  },

  {
    label: "10/11/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 60 },
      { label: "Company B", color: "#00cec9", image: "", value: 64 },
      { label: "Company C", color: "#0984e3", image: "", value: 61 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 80 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 42 },
      { label: "Company G", color: "#fab1a0", image: "", value: 28 },
      { label: "Company H", color: "#ff7675", image: "", value: 19 },
      { label: "Company I", color: "#fd79a8", image: "", value: 32 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 28 },
      { label: "Company K", color: "#e17055", image: "", value: 13 },
      { label: "Company L", color: "#d63031", image: "", value: 54 },
      { label: "Company M", color: "#e84393", image: "", value: 41 },
    ],
  },

  {
    label: "10/12/2021",
    bars: [
      { label: "Company A", color: "#00b894", image: "", value: 72 },
      { label: "Company B", color: "#00cec9", image: "", value: 80 },
      { label: "Company C", color: "#0984e3", image: "", value: 98 },
      { label: "Company D", color: "#6c5ce7", image: "", value: 111 },
      { label: "Company F", color: "#ffeaa7", image: "", value: 50 },
      { label: "Company G", color: "#fab1a0", image: "", value: 32 },
      { label: "Company H", color: "#ff7675", image: "", value: 20 },
      { label: "Company I", color: "#fd79a8", image: "", value: 34 },
      { label: "Company J", color: "#fdcb6e", image: "", value: 16 },
      { label: "Company K", color: "#e17055", image: "", value: 15 },
      { label: "Company L", color: "#d63031", image: "", value: 57 },
      { label: "Company M", color: "#e84393", image: "", value: 50 },
    ],
  },
];
